### ISSUE TITLE
Adicionar o campo "pagamento" nas telas de criar/editar "evento procedimento"

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/med_system#143]
- O usuario podera selecionar "convenio" ou "outros"
- A opcao "convenio" sera selecionada por default
- O campo "pagamento" deve ficar acima do campo "procedimento"

obs1: esse campo deve ser enviado para o servidor.
obs2: por hora vamos deixar impossivel para o usuario selecionar "outros", apenas enquanto o mobile/backend nao suporta toda a estrutura necessaria para o campo "outros".

**Comment by danielnottingham** [comment]
valores para o campo `payment`: `health_insurance `ou `others` do tipo String
