### ISSUE TITLE
Arrow button returns to Event Procedures list 

### ISSUE THREAD

**Issue by leonardobrito** [espoo-dev/med_system#83]
Flow:
 - Click on + button on Home Screen;
 - Click on Arrow Button to return;
 - Should display Home Screen Again. 
 
 
<img width="352" alt="Screenshot 2024-03-01 at 19 20 59" src="https://github.com/espoo-dev/med_system/assets/2532291/469151bc-89c7-4ee3-a38b-8d385476531e">
<img width="348" alt="Screenshot 2024-03-01 at 19 21 14" src="https://github.com/espoo-dev/med_system/assets/2532291/54fcae75-90f8-4490-81c1-6bd535a45dce">
<img width="352" alt="Screenshot 2024-03-01 at 19 21 24" src="https://github.com/espoo-dev/med_system/assets/2532291/c087ef32-5fda-4ef0-b1ac-25f4d626adf1">

**Comment by roandersonpinheiro** [comment]
Resolved.
