### ISSUE TITLE
Home screen does not update always

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/med_system#97]
![image](https://github.com/espoo-dev/med_system/assets/6463001/256ed441-e4db-4e8a-b713-a78db955dc0a)

**Comment by roandersonpinheiro** [comment]
Resolved

**Comment by edimossilva** [comment]
Video at whatsapp with label https://github.com/espoo-dev/med_system/issues/97

**Comment by edimossilva** [comment]
Fixed
