### ISSUE TITLE
Set fiels to be empty by default

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/med_system#98]
<img width="269" alt="Screenshot 2024-03-03 at 23 13 51" src="https://github.com/espoo-dev/med_system/assets/6463001/46bb6961-8cd8-4af9-9824-8cd2556b65c4">

E já deixar selecionado Enf ( maioria é Enf)

**Comment by roandersonpinheiro** [comment]
Resolved.

**Comment by edimossilva** [comment]
the `patient` field is still selected

**Comment by edimossilva** [comment]
fixed
